# Link: https://theweeklychallenge.org/blog/perl-weekly-challenge-277

CountCommon ← +´·⥊≡⌜○((1=≠¨)⊸/⊐⊸⊔)

# Tests
•Show ⟨"Perl", "is", "my", "friend"⟩ CountCommon ⟨"Perl", "and", "Raku", "are", "friend"⟩                                 # 2
•Show ⟨"Perl", "and", "Python", "are", "very", "similar"⟩ CountCommon ⟨"Python", "is", "top", "in", "guest", "languages"⟩ # 1
•Show ⟨"Perl", "is", "imperative", "Lisp", "is", "functional"⟩ CountCommon ⟨"Crystal", "is", "similar", "to", "Ruby"⟩     # 0
