# Link: https://theweeklychallenge.org/blog/perl-weekly-challenge-285

DeadEnds ← ⊢´¨(¬∘∊/⊣)⊑¨
         # (↑¨↓¨)«~»(↑¨) - Kap
         # ⊢/¨~⊃¨        - Dyalog APL
         # {⊃~/⌽↓⍉↑⍵}    - Dyalog APL (Alternative)
         # Ṫ€ḟḢ€         - Jelly
         # ↓¨~↑¨         - Hypothetical APL

# Tests
•Show DeadEnds ⟨⟨"B","C"⟩, ⟨"D","B"⟩, ⟨"C","A"⟩⟩ # "A"
•Show DeadEnds ⟨⟨"A","Z"⟩⟩                       # "Z"
