# Link: https://leetcode.com/problems/check-balanced-string

IsBalanced  ← (0‿1⥊˜≠)⊸×⊸((|∘-=⊣)○(+´))-⟜'0'¨
IsBalanced2 ← (2|↕∘≠)⊸×⊸((|∘-=⊣)○(+´))-⟜'0'¨
IsBalanced3 ← =´·+´¨·(¬⊸⋈2|↕∘≠)⊸(×⚇1)-⟜'0'¨
IsBalanced4 ← =´·+´˘·(¬⊸≍2|↕∘≠)⊸(×⎉1)-⟜'0'¨

# Tests
•Show IsBalanced "1234"  # 0
•Show IsBalanced "24123" # 1

•Show IsBalanced2 "1234"  # 0
•Show IsBalanced2 "24123" # 1

•Show IsBalanced3 "1234"  # 0
•Show IsBalanced3 "24123" # 1

•Show IsBalanced4 "1234"  # 0
•Show IsBalanced4 "24123" # 1
